version: "2"

services:
  web:
    image: dutchviking/dashpage.web:latest
    ports:
      - 3001:3000
    networks:
      - frontend
    volumes:
      - ~/workspace/nodejs/dashpage.web/dist:/usr/src/app/dist

  api:
    image: dutchviking/dashpage.api:latest
    ports:
      - 3000:3000
    networks:
      - frontend
      - backend
    links:
      - db:database

  db:
    image: mongo:latest
    volumes:
      - dbstore:/data/db
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  dbstore:
